;___________________________________________________________________
;___________________________________________________________________
;Copyright:	2015 by HOLTEK SEMICONDUCTOR INC
;File name:	IIC_Slave.inc
;Version: 	V00
;Targer:	HT68F002
;Author: 	ChenTing
;Date:		2015/05/21
;Description:IIC相關定義
;History: 
;___________________________________________________________________
;___________________________________________________________________
#define IIC_Device_Addr_Default 028H
#define IIC_Time_Out_Count		200